<ul>Python<ul>

<ul>      List-
      1>List is a non-homogeneous data structure that stores the elements in single row and multiple rows and columns.
      2>List can be represented by [ ]
      3>List allows duplicate elements
      4>List can be created using list() function
      5>List is mutable i.e we can make any changes in list.
      Example: [1, 2, 3, 4, 5]   <ul>

In [ ]:
#List-
     1>List is a non-homogeneous data structure that stores the elements in single row and multiple rows and columns.
     2>List can be represented by [ ] 
     3>List allows duplicate elements 
     4>List can be created using list() function 
     5>List is mutable i.e we can make any changes in list. Example: [1, 2, 3, 4, 5]


In [ ]:
#Tuple-
       1>Tuple is also a non-homogeneous data structure that stores single row and multiple rows and columns
       2>Tuple can be represented by ()
       3>Tuple allows duplicate elements
       4>Tuple can be created using tuple() function
       5>Tuple  is immutable i.e we can not make any changes in tuple
       Example: (1, 2, 3, 4, 5)

In [ ]:
#sets-
      1>Set data structure is also non-homogeneous data structure but stores in single row
      2>Set can be represented by { }
      3>Set will not allow duplicate elements
      4>Set can be created using set() function
      5>Set is mutable i.e we can make any changes in set. But elements are not duplicated.
      Example: {1, 2, 3, 4, 5}

In [ ]:
#Dictionary-
      1>Dictionary  is also non-homogeneous data structure but stores in single row
      2>Dictionary can be represented by { }
      3>Set will not allow duplicate elements and dictionary doesn’t allow duplicate keys.
      4>Dictionary can be created using dict() function.
      5>Dictionary is mutable. But Keys are not duplicated.
      Example: {1, 2, 3, 4, 5}

In [1]:
3**2

9

In [3]:
231%10

1

In [4]:
231//10

23

In [24]:
#234=2*3*4=24
i=int(input())
while i>0:
    prod=prod*(i%10)
    i=i//10
print(prod)

234
24


In [2]:
#EX-231-(2^3+3^3+1^3)=36
i=int(input())
sum=0
while i >0:
    sum=sum+(i%10)**3
    i=i//10
print(sum)

231
36


In [14]:
#Amstrang no -153-1^3+5^3+3^3=153-yes
i=int(input())
count=0
n=i
while (i>0):
    i=i//10
    count=count+1
sum=0
i=n
while(i>0):
    digit=i%10
    x=1
    prod=1
    while(x<=count):
        prod=prod*digit
        x=x+1
    sum=sum+prod
    i=i//10
if n==sum:
    print('Amstrang')
else:
    print('No')

153
Amstrang


In [23]:
#Amstrang no -153-1^3+5^3+3^3=153-yes
i=int(input())
n=i
count=0
while(i>0):
    i=i//10
    count=count+1
i=n
sum=0
while (i>0):
    sum=sum+(i%10)**count
    i=i//10
if n == sum:
    print('yes')
else:
    print('no')

153
yes


In [25]:
#Reverse-237=732
i=int(input())
rev=0
while i>0:
    rev=(rev*10)+(i%10)
    i=i//10
print(rev)

237
732


In [26]:
#palidrome no-525-525
i=int(input())
rev=0
n=i
while i >0:
    rev=(rev*10)+(i%10)
    i=i//10
if (rev==n):
    print("Palidrome no")
else:
    print("Not A Palidrome no")

525
Palidrome no


In [27]:
#Check given no prime or not ;Ex-13=13 can be divide by 1 and 13 only
n=int(input())
i=1
count=0
while n >= i:
    if n%i ==0:
        count=count+1
    i=i+1
if count==2:
    print('This is prime no')
else:
    print('composite no')

13
This is prime no


In [1]:
#Factorical-Ex-5=5*4*3*2*1
i=int(input())
F=1
while i>0:
    F=F*(i%10)
    i=i-1
print(F)

5
120


In [2]:
#Nasted Loop for Star pattern
i=5
while i>0:
    j=1
    while j<=i:
        print("*",end=" ")
        j=j+1
    print()
    i=i-1

* * * * * 
* * * * 
* * * 
* * 
* 


In [3]:
n=5
for i in range(n+1):
    for j in range(i):
        print('*',end=' ')
    print( )


* 
* * 
* * * 
* * * * 
* * * * * 


In [4]:
#Nasted Loop for Star pattern
i=1
while i <=5:
    j=1
    while j<=i:
        print("*",end=" ")
        j=j+1
    print()
    i=i+1

* 
* * 
* * * 
* * * * 
* * * * * 


In [5]:
n=5
for i in range(n):
    for j in range(1,n-1):
        print(" ",end =" ")
    for k in range(0,i+1):
        print("*",end=' ')
    print( )

      * 
      * * 
      * * * 
      * * * * 
      * * * * * 


In [6]:
i=1
while i<=5:
    j=1
    while j<=i:
        print(j,end=" ")
        j=j+1
    print()
    i=i+1

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [7]:
i=1
while i<=5:
    j=1
    while j<=i:
        print(i,end=" ")
        j+=1
    print()
    i+=1

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [8]:
i=1
while i<=5:
    b=1
    while (b<=5-i):
        print("-",end=" ")
        b+=1
    j=1
    while j<=i:
        print("*",end=" ")
        j+=1
    print()
    i+=1 

- - - - * 
- - - * * 
- - * * * 
- * * * * 
* * * * * 


In [9]:
i=1

while i<=5:
    b=1
    while b<=(5-i):
        print("-",end=" ")
        b+=1
   
    j=1
    while j<=i:
        print(j,end=" ")
        j+=1
    print()
    i+=1

- - - - 1 
- - - 1 2 
- - 1 2 3 
- 1 2 3 4 
1 2 3 4 5 


In [10]:
i=1

while i<=5:
    b=1
    while b<=(5-i):
        print("-",end=" ")
        b+=1
   
    j=1
    while j<=i:
        print(i,end=" ")
        j+=1
    print()
    i+=1

- - - - 1 
- - - 2 2 
- - 3 3 3 
- 4 4 4 4 
5 5 5 5 5 


In [11]:
i=5
while i>0:
    j=1
    while j< i:
        print("*",end=" ")
        j+=1
   
    b=1
    if i==1:
        break
    while b<=(6-i):
        print("_",end=" ")
        b+=1
    print()
    i-=1

* * * * _ 
* * * _ _ 
* * _ _ _ 
* _ _ _ _ 


In [1]:
#square pattern
n=int(input())
for i in range(n):
    for j in range(n):
        print('*',end=" ")
    
    print()

5
* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [2]:
#hollow pattern
n=int(input())
for i in range(n):
    for j in range(n):
        if i== 0 or i==n-1 or j==0 or j==n-1:
            print('*',end=" ")
        else:
            print(' ',end=" ")
    print()

5
* * * * * 
*       * 
*       * 
*       * 
* * * * * 


In [5]:
#Reverse the alphabet order
x=input()
#keep input in same formte as inside of bracket in split
y=x.split(',')
z=y[::-1]
#keep input in same formte as inside of curly brackets in join
q=" ,".join(z)
print(x)
print(y)
print(z)
print(q)


night,sight,kj,ol
night,sight,kj,ol
['night', 'sight', 'kj', 'ol']
['ol', 'kj', 'sight', 'night']
ol ,kj ,sight ,night


In [6]:
x=input()
x=x.capitalize()
z=x.split(' ')
q='_'.join(z)
print(x)
print(z)
print(q)

i love u hgf
I love u hgf
['I', 'love', 'u', 'hgf']
I_love_u_hgf


In [7]:
#Reverse order 
x=input()
x=x.lower()
y=x[::-1]
print(x)
print(y)
if x==y:
    print("Palidrome")
else:
    print ('Not at all')

HJJJK
hjjjk
kjjjh
Not at all


In [8]:
s1=input().lower()
s2=input().lower()
if (sorted(s1)==sorted(s2)):
    print('plaidrome')
else:
    print('no')

hmh
HMH
plaidrome


In [9]:
s1=input().lower()
s2=input().lower()
x=[]
for i in range (min(len(s1),len(s2))):
    x.append(s1[i])
"".join(x)


upgrad
upgardyui


'upgrad'

In [10]:
s1=input().lower()
s2=input().lower()
for i in range (min(len(s1),(len(s2)))):
    if s1[i]!=s2[i]:
        break
if s1[i]!=0:
    print(s1[ : i+1])

upgard
upgardscience
upgard


In [11]:
#swapping
x=input()
y=input()
print('Before swaping',x)
print('Before swaping',y)

z=x
x=y
y=z
print()
print()

print('After swaping',x)
print('After swaping',y)


school
child
Before swaping school
Before swaping child


After swaping child
After swaping school


In [12]:
#Even and odd
x=int(input())
if x % 2==0:
    print("Even")
else:
    print('odd')

6
Even


In [14]:
x=int(input())
if x%3==0:
    print('Beautifull')
elif x%3==1:
    print('Just ok')
else:
    print('Bhoot')

50
Bhoot


In [16]:
no=int(input())
def factorial(x):
    if x<0:
        return -1
    else:
        F=1
        for i in range (1,x+1):
            F=F*i
        return F
k=factorial(no)
print(k)

5
120


In [17]:
L=[i for i in range (1,5)]
print(L)
print(L.index(4))
k=10 in L
k

[1, 2, 3, 4]
3


False

In [1]:
# To find out samllest No
import ast
x=ast.literal_eval(input())
m=x[0]
for i in x:
    if i<m:
        m=i
print(m)

30,50,80,90
30


In [2]:
#Average+smallest value find out
import ast
Q=ast.literal_eval(input())
sum=0
for i in Q:
    sum=sum+i
R=sum/len(Q)
print(R)
X=Q[0]
for i in Q:
    if i<X:
        X=i
print(X)
    

30,120,70,50
67.5
30


In [4]:
#Wedding calsh
import ast
x=ast.literal_eval(input())
y=int(input())
clash=0
#for i in x:
#    if i==y:
#        clash=clash+1
#print(clash)
z=x[0]
for i in x:
    if i > y and z < y:
        clash=clash+1
    z=i
print(clash)

10,20,30,60
35
1


In [ ]:
# string Always Immutable
#chr(123)-for  ASCII code is 123.
#S.strip()-Remove empty spaces from both ends of the string

In [5]:
import ast
x=input()
x=x.split(",")
y=('G').join(x)
print(y)
print(x)
#x=input()
#keep input in same formte as inside of bracket in split
#y=x.split(' ,')
#z=y[::-1]
#keep input in same formte as inside of curly brackets in join
#q=" ,".join(z)

up,grade
upGgrade
['up', 'grade']


In [8]:

y=('G').join(["UP",'RAD'])
y


'UPGRAD'

In [11]:
x1=input()
x=set(x1)
y=('G').join(x)
y

upgrad


'pGaGrGdGgGu'

In [10]:
s='upiu'.strip('u')
s

'pi'

In [12]:
s='aabupGradaab'.strip('a').strip('b').strip('a')
s

'upGrad'

In [1]:
y=('G').join(["UP",'RAD'])

In [2]:
x1=input()
x=set(x1)
y=('G').join(x)
y

tr,kj


'rGkGjG,Gt'

In [3]:
s='upiu'.strip('u')
s

'pi'

In [ ]:
s='aabupGradaab'.strip('a').strip('b').strip('a')
s

In [4]:
#Palidrome
x=input()
r=''
for i in x:
    r=i+r
if r==x:
    print("Palidrome")
else:
    print('NO')
    

hmh
Palidrome


In [5]:
#Palidrome-2nd Method
s1=input().lower()
s2=input().lower()
if sorted(s1)==sorted(s2):
    print('Palidrome')
else:
    print('NO Palidrome')

raaar
raaar
Palidrome


In [6]:
#Reverse
x=input()
x=x.split(' ')
x=x[::-1]
y=(' ').join(x)
print(y)

i love coding
coding love i


In [7]:
#join
x=input()
x=x.capitalize()
x=x.split(' ')
y=('_').join(x)
print(y)

SAGH yuu
Sagh_yuu


In [8]:
L=[]
for i in range(1,5):
    L.append(i)
print(L)

[1, 2, 3, 4]


In [1]:
L=[i for i in range(1,5)]
L

[1, 2, 3, 4]

In [2]:
L.index(4)

3

In [3]:
k=10 in L
k

False

In [4]:
L=[10,20,30,40,50,60,70,80,90,100,110]
L[1::-1]

[20, 10]

In [5]:
L=[10,20,30,40,50,60,70,80,90,100,110]
L[::-1]

[110, 100, 90, 80, 70, 60, 50, 40, 30, 20, 10]

In [6]:
#Smallest Value find out 
import ast
x=ast.literal_eval(input())
y=x[0]
for i in x:
    if y>i:
        y=i
print(y)

10,30,80,5,8
5


In [7]:
x=input()
y='aeiouAEIOU'
t=''
r=''
for i in x:
    if i in y:
        t=t+i
    else:
        r=r+i
    s=t+r
print(s)

#You love Python!
#ouoeoY lv Pythn!   
    

You love Python!
ouoeoY lv Pythn!


In [8]:
s1=input()
s2=input()
L=''
for i in range (min(len(s1),len(s2))):
    if s1[i]==s2[i]:
        L=L+s1[i]
    else:
        break
print(L)

upgrad
upgrader
upgrad


In [9]:
s1=input()
s2=input()
L=[]
for i in range (min(len(s1),len(s2))):
    if s1[i]==s2[i]:
        L.append(s1[i])
    else:
        break
print(''.join(L))

upgrad
upgrader
upgrad


In [ ]:
#set.intersection(A, B, C)-interscation will not work in sets
#Tuples are immutable
#sets are mutable
#d.keys()/d.values() returns a list of all keys.
#del dict_1['R']-R is key

In [1]:
#Remove Deplicate
import ast
r=input()
q=ast.literal_eval(r)
l=[]
for i in q:
    if i not in l:
        l.append(i)
print(l)



[1,666,7,7,7,9,10]
[1, 666, 7, 9, 10]


In [3]:
a=['Ram','Shyam','Ram','Satish']
a.count('Ram')
print(a)
y=a.index('Ram')
print(y)
a.insert(1,'Rahul')
print(a)
a.remove('Rahul')
print(a)
a.reverse()
print(a)
d=len(a)
print(d)
a.sort()
print(a)
a.pop()
print(a)

['Ram', 'Shyam', 'Ram', 'Satish']
0
['Ram', 'Rahul', 'Shyam', 'Ram', 'Satish']
['Ram', 'Shyam', 'Ram', 'Satish']
['Satish', 'Ram', 'Shyam', 'Ram']
4
['Ram', 'Ram', 'Satish', 'Shyam']
['Ram', 'Ram', 'Satish']


In [4]:
x1=(1,2,3,4,5)
x2=(6,7,8,9,10)
x3=x1+x2
print(x3)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [5]:
x1=[1,2,3,4,5]
x2=[6,7,8,9,10]
x3=x1+x2
print(x3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [6]:
x1=[1,2,3,4,5]
x2=x1*3
print(x2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [7]:
x1=[1,2,3,4,5]
x2=[6,7,8,9,10]
max(x1)
min(x2)
x1.count(2)
print(x1)
x1.insert(2,20)
x1


[1, 2, 3, 4, 5]


[1, 2, 20, 3, 4, 5]

In [8]:
x=int(input())
a=[]
for i in range(x):
    y=int(input('Enter value' ))
    a.append(y)
print(a)
sum=0
for i in range(x):
    sum=sum+i
print(sum)

5
Enter value5
Enter value1
Enter value2
Enter value5
Enter value4
[5, 1, 2, 5, 4]
10


In [9]:
x=int(input())
a=[]
for i in range(x):
    y=int(input('Enter value' ))
    a.append(y)
print(a)
sum=0
for i in range(x):
    sum=sum+a[i]
print(sum)

3
Enter value10
Enter value20
Enter value30
[10, 20, 30]
60


In [10]:
s1=input()
s2=input()
L=''

for i in range (min(len(s1),len(s2))):
    if s1[i]==s2[i]:
        L=L+s1[i]
    else:
        break
print(L)

upgrad
upgradeee
upgrad


In [11]:
#extract=love
S ='I love Python'
S[-11:-7]
S[2:6]



'love'

In [12]:
L1=['AUTO','HONDA','GM']
L2=[10,20,30]
for i ,j in zip(L1,L2):
    print(i,'-',j)

AUTO - 10
HONDA - 20
GM - 30


In [14]:
import sys
pin=int(input('Enter pin no-' ))
count=0
if pin!=1234:
    if pin==2580:
        print('Vaild pin')
    elif count<=3:
        pin=int(input('Enter pin no-' ))
        print('wrong pin code.Try gain')
        count=count+1
        print('invaild pin.card blocked')
#sys exit('Too many invild attempt')
        
        
        

Enter pin no-8523
Enter pin no-4561
wrong pin code.Try gain
invaild pin.card blocked


In [15]:
D = {1:['Raj', 22], 2:['Simran', 21], 3:['Rahul', 40]}
l=[]
for value in D:
    l.append(value)
print(l)

[1, 2, 3]


In [16]:
d={'brand':'suzuki','model':'desire','year':2010}
print(d)
d['model']


{'brand': 'suzuki', 'model': 'desire', 'year': 2010}


'desire'

In [17]:
d={'brand':'suzuki','model':'desire','year':2010}
print(d)
d.get('brand')

{'brand': 'suzuki', 'model': 'desire', 'year': 2010}


'suzuki'

In [18]:
d={'brand':'suzuki','model':'desire','year':2010}
l=[]
for i in d:
    l.append(d[i])
print(l)

['suzuki', 'desire', 2010]


In [19]:
d={'brand':'suzuki','model':'desire','year':2010}
l=[]
for i in d:
    l.append(i)
print(l)

['brand', 'model', 'year']


In [1]:
d={'brand':'suzuki','model':'desire','year':2010}
for x,y in d.items():
    print(x,y)

brand suzuki
model desire
year 2010


In [2]:
d={'brand':'suzuki','model':'desire','year':2010}
for x in d.keys():
    print(x)
for y in d.values():
    print(y)
d.pop('model')
d

brand
model
year
suzuki
desire
2010


{'brand': 'suzuki', 'year': 2010}

In [3]:
d={'brand':'suzuki','model':'desire','year':2010}
d.setdefault('my_car','toyota')
d

{'brand': 'suzuki', 'model': 'desire', 'year': 2010, 'my_car': 'toyota'}

In [4]:
d={'brand':'suzuki','model':'desire','year':2010}
d.update({'location':'delhi'})
d

{'brand': 'suzuki', 'model': 'desire', 'year': 2010, 'location': 'delhi'}

In [5]:
d={'brand':'suzuki','model':'desire','year':2010}

d.clear()
d

{}

In [ ]:
#Array
#-Boolean value is defined without the apostrophes-""-dont use in true
#s=(1.0, 2, 3.5, 0.2, True)
# it is possible to create an array from a tuple.

In [6]:
import numpy as np
import ast
s=input()
q=ast.literal_eval(s)
m=int(input())
n=int(input())
array_1=np.array(q)
#final_array=array_1
[(array_1 > m)& (array_1 < n)]
final_array = array_1 [(array_1 >= m) & (array_1 <=n)]
print(final_array)

10,20,30,40,50
10
20
[10 20]


In [7]:
import numpy as np
x=np.ones((2,2))
x

array([[1., 1.],
       [1., 1.]])

In [8]:
import numpy as np
x=np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
import numpy as np
x=np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
import numpy as np
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [4]:
import numpy as np
arr=np.random.randint(1,10,9)
arr1=arr.reshape(3,3)
arr
arr1

array([[7, 5, 8],
       [6, 5, 4],
       [2, 4, 2]])

In [5]:
import numpy as np
arr=np.random.rand(5)
arr

array([0.71971239, 0.05262733, 0.69559938, 0.25602762, 0.28068971])

In [6]:
import numpy as np
arr=np.random.randint(1,10,9)
print(arr)
arr1=arr.reshape(3,3)
arr1[arr1 % 2==0]=0
print(arr1)
b=arr1[arr1>5]
b

[9 5 8 7 8 9 9 7 1]
[[9 5 0]
 [7 0 9]
 [9 7 1]]


array([9, 7, 9, 9, 7])

In [7]:
import numpy as np
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [8]:
arr+2

array([3, 4, 5, 6])

In [9]:
arr*2

array([2, 4, 6, 8])

In [10]:
arr**2

array([ 1,  4,  9, 16], dtype=int32)

In [11]:
np.linspace(1,10,5)
#10 included

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
x=np.random.randint(1,10,5)
#10 not included

In [14]:
np.random.rand(1,10,5)

array([[[0.08294971, 0.10500637, 0.26864511, 0.7820162 , 0.55328849],
        [0.83877234, 0.47938779, 0.44387974, 0.51592329, 0.15367459],
        [0.84697579, 0.08866956, 0.82696602, 0.60812452, 0.16107857],
        [0.34524314, 0.57981928, 0.9944306 , 0.55749666, 0.53571559],
        [0.80168774, 0.70154427, 0.79552518, 0.72319901, 0.89624212],
        [0.62996929, 0.18403215, 0.18980861, 0.24069741, 0.36032005],
        [0.11068365, 0.91320112, 0.4031737 , 0.9994755 , 0.80265981],
        [0.27300922, 0.58088041, 0.94176427, 0.64661665, 0.49511147],
        [0.65329743, 0.23311264, 0.27384322, 0.84160386, 0.62633165],
        [0.65468302, 0.98021676, 0.08015283, 0.74611706, 0.29660414]]])

In [17]:
import numpy as np
x=([10,20,30,40,50])
np.min(x)
np.sqrt(x)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [18]:
np.max(x)

50

In [19]:
np.power(x,3)

array([  1000,   8000,  27000,  64000, 125000], dtype=int32)

In [20]:
np.multiply(x,12)

array([120, 240, 360, 480, 600])

In [21]:
np.searchsorted(x,30)

2

In [22]:
y=np.where(x==40)
print(y)

(array([], dtype=int64),)


In [23]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
b.ndim

2

In [26]:
b.shape

(3, 3)

In [27]:
b.size

9

In [28]:
b.dtype

dtype('int32')

In [29]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
b[:2,1:3]

array([[1, 2],
       [4, 5]])